import './globals.css'
import { Montserrat } from "next/font/google"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700"]
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="bg-primary-light" lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
